#boll策略每天在下午运行几次就行。因为开盘后，原有买卖信号会消失，而新的不会出现。因此买卖最好在下午进行。
#设置一天运行多次.避开高峰分钟段(如每小时的07、23、37、53)。
#因为工作流延迟触发时超过下一个触发时间，则下一个触发时间就不会执行了。因此执行间隔设置小一点
name: boll均值回归策略-监控

on:
  schedule:
    - cron: '07 5 * * 1-5'  # 13:07 CST
    - cron: '37 5 * * 1-5'  # 13:37 CST
    - cron: '53 5 * * 1-5'  # 13:53 CST
    - cron: '23 6 * * 1-5'  # 14:23 CST

  workflow_dispatch:

jobs:
  BollStrategy-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置Python3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install akshare pandas requests

    - name: 运行监控程序
      run: python BollStrategy_monitor.py
