name: ETF溢价率每日记录及持有ETF溢价率预警

on:
  schedule:
    - cron: '15 3 * * 1-5' #每周1-5 早11点15分 开始
  workflow_dispatch:

jobs:
  run-ETF_script:    #任务名称
    runs-on: ubuntu-latest  # 选择运行环境

    steps:
    - name: Checkout repository    #步骤的名称
      uses: actions/checkout@v4   #检出仓库的代码

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 选择Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare pandas requests
        
    - name: Run ETF_PremiumRate_Record_Alert.py script
      run: |
        python ETF_PremiumRate_Record_Alert.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add etf_premium_rates.csv actions_running_log.txt
        git commit -m 'Update ETF premium rates and log'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload ETF Premium Rates CSV
      uses: actions/upload-artifact@v2
      with:
        name: etf-premium-rates
        path: etf_premium_rates.csv

    - name: Upload Log File
      uses: actions/upload-artifact@v2
      with:
        name: etf-premium-rates-log
        path: actions_running_log.txt
