name: ETF溢价率每日记录及持有ETF溢价率预警

on:
  schedule:
    - cron: '15 3 * * 1-5' # 每周1-5 早11点15分 开始
  workflow_dispatch:

jobs:
  run-ETF_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare pandas requests
        
    #- name: Download previous artifacts
      #uses: actions/download-artifact@v2
      #with:
        #name: etf-premium-rates
        #path: ./artifacts

    - name: Run ETF_PremiumRate_Record_Alert.py script
      run: python ETF_PremiumRate_Record_Alert.py
      env:
        CSV_PATH: ./artifacts/etf_premium_rates.csv

    - name: Upload ETF Premium Rates CSV
      uses: actions/upload-artifact@v2
      with:
        name: etf-premium-rates
        path: ./artifacts/etf_premium_rates.csv
