name: 监控基金的申购状态

on:
  schedule:
    - cron: '15 3 * * 1-5' #每周1-5 早11点15分 开始
  workflow_dispatch:

jobs:
  run-script:    #任务名称
    runs-on: ubuntu-latest  # 选择运行环境

    steps:
    - name: Checkout repository    #步骤的名称
      uses: actions/checkout@v4   #检出仓库的代码

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 选择Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare requests
        
    - name: Run monitor_funds script
      run: |
        python monitior_fund_subscription_status.py

    - name: Commit and push changes
      run: |
        git config --global user.email "[email protected]"
        git config --global user.name "github-actions[bot]"
        git add actions_running_log.txt
        git commit -m "Update fund_subscription_status running log"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
