#每天运行三次
name: 坚持只投纳指-监控

on:        
  schedule:      
  - cron: '07 0 * * 1-5'  # 8:07
  - cron: '23 0 * * 1-5'  # 8:23
  - cron: '37 0 * * 1-5'  # 8:37
  - cron: '53 0 * * 1-5'  # 8:53

  workflow_dispatch:

jobs:
  OnlyNDX_stock_monitor_monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 设置Python3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install akshare pandas requests

    - name: 运行监控程序
      run: python OnlyNDX_stock_monitor.py
