name: 每日定时运行监控脚本

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC凌晨1点25分 对应北京时间早9点25分
    - cron: '30 16 * * *'
    #push:    #推送到任意分支后运行

jobs:
  run-script:    #任务名称
    runs-on: windows-latest  # 选择运行环境

    steps:
    - name: Checkout repository    #步骤的名称
      uses: actions/checkout@v4   #检出仓库的代码

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # 选择Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install akshare requests
        
    - name: Run Python script
      run: |
        python stock_monitor.py
